# THEME DEPLOYMENT WORKFLOW
# -------------------------
# This workflow is ran manually by clicking the "Run workflow" button in the Github Actions tab

# NOTE: JSON config files will not be pushed as they are being ignored in the .shopifyignore file

# Required Github enviroment secrets / variables:
# - SHOPIFY_CLI_THEME_TOKEN: Shopify CLI token
# - SHOPIFY_FLAG_STORE: Shopify store URL

# These need to be added via the Github repo settings under "Environments"

name: Deploy theme

on:
  workflow_dispatch:
    inputs:
      store:
        description: 'Store'
        type: environment
        required: true
      theme_override:
        description: 'Theme Override'
        type: string
      publish_theme:
        description: 'Publish Theme'
        type: boolean
        default: false
      source_theme:
        description: 'Source Theme ID (optional). By default, JSON content is synced from the published theme. Use this to sync JSON content from a draft theme instead.'
        type: string

run-name: Deploying ${{ github.head_ref || github.ref_name || github.ref || github.event.ref }} to ${{ inputs.store }} (@${{ github.actor }})

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: ${{ inputs.store }}
    env:
      SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
      SHOPIFY_FLAG_STORE: '${{ vars.SHOPIFY_FLAG_STORE }}'
    steps:
      - uses: actions/checkout@v5

      - name: Validate theme IDs if source theme is set
        if: ${{ inputs.source_theme != '' }}
        run: |
          if [[ -n "${{ inputs.theme_override }}" && -n "${{ inputs.source_theme }}" && "${{ inputs.theme_override }}" == "${{ inputs.source_theme }}" ]]; then
            echo "❌ ERROR: theme_override and source_theme cannot be the same ID!"
            echo "theme_override: ${{ inputs.theme_override }}"
            echo "source_theme: ${{ inputs.source_theme }}"
            echo "This would cause the theme to sync JSON content from itself, which is not allowed."
            exit 1
          fi
          echo "✅ Theme Override and Source Theme ID validation passed"

      - uses: actions/setup-node@v5
        with:
          node-version: 18

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@3.85.4

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npx turbo build

      - uses: meetdomaine/shopify-duplicate-theme@v2.0.0
        id: duplicate
        if: ${{ inputs.theme_override == '' }}
        with:
          store: '${{ env.SHOPIFY_FLAG_STORE }}'
          env: ${{ inputs.store }}-${{ github.head_ref || github.ref_name || github.ref || github.event.ref }}
          source-theme-id: ${{ inputs.source_theme != '' && inputs.source_theme || null }}
          # max-wait-minutes: 10
          # check-interval-seconds: 30
          

      - name: Deploy theme
        run: shopify theme push --theme $THEME_ID
        if: ${{ inputs.store }} && ${{ github.head_ref || github.ref_name || github.ref || github.event.ref }}
        env:
          # Theme ID is read from variable of previous step
          THEME_ID: ${{ inputs.theme_override == '' && steps.duplicate.outputs.themeId || inputs.theme_override }}

      - uses: meetdomaine/shopify-jsons-sync@v1.5.2
        # This action is used to sync new JSON content (locale strings & JSON templates) to the theme
        # Note: No existing content on the theme being deployed too will be edited or pushed
        with:
          store: '${{ env.SHOPIFY_FLAG_STORE }}'
          theme: ${{ inputs.theme_override == '' && steps.duplicate.outputs.themeId || inputs.theme_override }}
          source-theme: ${{ inputs.source_theme != '' && inputs.source_theme || null }}

      - name: Publish theme
        run: shopify theme publish --theme $THEME_ID --force
        if: ${{ inputs.publish_theme }}
        env:
          # Theme ID is read from variable of previous step
          THEME_ID: ${{ inputs.theme_override == '' && steps.duplicate.outputs.themeId || inputs.theme_override }}
